### ISSUE TITLE
what about filtering words in api response instated of replace them in js

### ISSUE THREAD

**Issue by n0099** [justoverclockl/flarum-ext-purify#4]
https://github.com/justoverclockl/flarum-ext-purify/blob/a1819d8d20a8d834c2567d99fde23cf8cb0ec735/js/src/forum/PurifyText.js#L20-L30
This issue is similar with https://github.com/justoverclockl/flarum-ext-emoticonpack/issues/2, and just as #2 said if we can filter words in [render event of s9e\TextFormatter](https://docs.flarum.org/extend/formatting), then it will be more completely to remove word since they are not visible to the search engines including flarum's own one and google.
But I'm not sure is flarum just searching the keywords in all posts or in rendered html, if it's using the proper one (probably is) we might have to filter words on posts created and edited event in api backend, resulting in unable to undo ban on words and adding words won't affected existing posts.

**Comment by justoverclockl** [comment]
feel free to submit a pr with your solution :)

**Comment by n0099** [comment]
> to filter words on posts created and edited event in api backend

can be achieved by replacing post content in parse phase of TextFormatter:
```php
return [
    (new Extend\Formatter)
        ->parse(function ($_p, $_c, $text) {
            return str_replace('fuck', 'f**k', $text);
        })
];
```
and we can even do a reverse replace to revert the filtering when unparsing: https://s9etextformatter.readthedocs.io/Getting_started/Unparsing/, of course within the unparse phase it's impossible to distinguish a literal 'f**k' (user typed the filtered words as is) and the one previously replaced by parse().
